### ISSUE TITLE
[feedback] Ebuild rust 1.31.1, 2 small issue

### ISSUE THREAD

**Issue by g3ngr33n** [smaeul/portage-overlay#17]
Hello,

Many thanks for your contribution, I appreciate it. Your ebuild work nicely despite 2 small issue while emerging

Build log available at : https://paste.pound-python.org/show/cvXrswfIZry6kjOqMifv/

line 83 : rustc_promotable
The fix seems to be already made 
https://github.com/rust-lang/rust/pull/55828/files

line 714 : miri failed to run custom build
If guess it is related to the crate vergen which use the version 3.0.3 instead of 3.0.4, similar bug with the fix here :https://github.com/rust-lang/rust/issues/56576

**Comment by smaeul** [comment]
Thanks for the reports.

The `rustc_promotable` warnings can be ignored. The PR you linked is actually what is causing the warnings. It looks like the attributes are ignored because they affect some newer feature that's not in 1.31.

Miri is known not to compile. In fact the `::gentoo` ebuild completely excludes it from the build. I could do the same here, but I don't think it makes a difference.
