### ISSUE TITLE
sys-libs/libssp_nonshared: file collision with at musl-1.2.1-r2?

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#27]
hey there, I've encountered a file collision when sys-libs/libssp_nonshared from your overlay is emerged and sys-libs/musl::gentoo was upgrade to musl-1.2.1-r2. It seems that musl nowadays ships it's own `/usr/lib/libssp_nonshared.a` ; maybe you want to add a blocker to your sys-libs/libssp_nonshared ebuild? 

also your https://portage.smaeul.xyz/distfiles/ archive seems down

hope to help you with this message :)

**Comment by smaeul** [comment]
Thanks for the notification. Unfortunately, adding a blocker would not help, since you already have the package installed. And revbumping the package to add the blocker would just result in portage keeping the old version. In fact, I should remove the package entirely. I will update the `dev-lang/rust` dependency and drop `sys-libs/libssp_nonshared`.

As for the server, its location is experiencing an Internet outage.

**Comment by stefson** [comment]
I think this was mitigated in https://github.com/smaeul/portage-overlay/commit/7cfd5c2a9c5c28be98c8d698280a4f94aa34e937 , thank you :)
