### ISSUE TITLE
dev-lang/rust and dev-util/cargo fail to build on amd64

### ISSUE THREAD

**Issue by stefson** [smaeul/portage-overlay#9]
I did the compile and runtime testing for both rust and cargo with 30f5a8c96ef607b9ef6f84bae657497efe75f1f8, now with the current git head they fail. It seems something got wrong since then? From the logs, it seems like a linking error for cargo, but no idea about the reason for the rust compile failure

build logs and emerge --info for you: [logs.zip](https://github.com/smaeul/portage-overlay/files/1430783/logs.zip)

**Comment by smaeul** [comment]
It looks like you got SIGSEGV in rustc ("`exit code: 139`", which is 128 + the value of SIGSEGV, 11). That's a bug somewhere, possibly related to https://github.com/rust-lang/rust/issues/38618, but it's not from the patches in the overlay. Please try compiling rust again. The cargo error is because you need the new rust for the default linkage type to be dynamic. Cargo should depend on the new revision of rust, but I forgot to do that.

**Comment by stefson** [comment]
Well, it passed for now, and with -r1 rustc cargo built fine withouth the linking error. Personally I think that this was a regression in musl itself, I built and tested 30f5a8c96ef607b9ef6f84bae657497efe75f1f8 against a 1.1.16 toolchain, the error above happend as I upgraded to 1.1.17 and then tried to built against new toolchain. With 1.1.18 all is fine.
